groups:
# - name: experimentation
#   jobs: 
#   - test-pr
#   - release
#   - create-pr


resource_types:
# https://github.com/cloudfoundry-community/slack-notification-resource
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
- name: pull-request-test
  type: docker-image
  source:
    repository: jtarchie/pr
    tag: test

resources:
# Code for all Fission Functions
- name: fission-function-src
  type: git
  source:
    uri: git@github.com:OpenIndustryCloud/fission-wf-storm-surge.git
    branch: master
    private_key: ((gh-ssh-key))
# Code from dependencies
- name: fission-go-add-risk-data-src
  type: git
  source:
    uri: git@github.com:OpenIndustryCloud/fission-go-add-risk-data.git
    branch: workflow
    private_key: ((gh-ssh-key))
- name: fission-go-compute-weather-risk-src
  type: git
  source:
    uri: git@github.com:OpenIndustryCloud/fission-go-compute-weather-risk.git
    branch: workflow
    private_key: ((gh-ssh-key))
- name: fission-go-form-req-transformer-src
  type: git
  source:
    uri: git@github.com:OpenIndustryCloud/fission-go-form-req-transformer.git
    branch: workflow
    private_key: ((gh-ssh-key))
- name: fission-go-register-ticket-src
  type: git
  source:
    uri: git@github.com:OpenIndustryCloud/fission-go-register-ticket.git
    branch: workflow
    private_key: ((gh-ssh-key))
- name: fission-go-weather-data-src
  type: git
  source:
    uri: git@github.com:OpenIndustryCloud/fission-go-weather-data.git
    branch: workflow
    private_key: ((gh-ssh-key))

# Code for CI unitasks 
- name: oic-ci-tasks-src
  type: git
  source:
    uri: git@github.com:OpenIndustryCloud/oic-ci-tasks
    branch: master
    disable_ci_skip: true
    private_key: ((gh-ssh-key))
# Slack Definitions
# - name: slack-alert-infra
#   type: slack-notification
#   source:
#     url: ((slack-url-infra))
# - name: slack-alert-buildbot
#   type: slack-notification
#   source:
#     url: ((slack-url-buildbot))
# Docker Images
- name: docker-image-fission-cli
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-fission-cli))
- name: docker-image-newman
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-newman))
- name: docker-image-wfcli
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-wfcli))
- name: docker-image-go-builder
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-go-builder))

# Pull Requests
- name: fission-function-pr
  type: pull-request
  source:
    access_token: ((gh-access-token))
    private_key: ((gh-ssh-key))
    repo: OpenIndustryCloud/fission-wf-storm-surge
    base: master
- name: fission-function-merge-pr
  type: pull-request-test
  source:
    access_token: ((gh-access-token))
    private_key: ((gh-ssh-key))
    base: test-merge
    repo: OpenIndustryCloud/fission-wf-storm-surge

jobs:
#####################################################################
#
# Test PR Management
#
#####################################################################
- name: publish-requirements
  public: true
  plan:
  - aggregate:
    - get: docker-image-fission-cli
    - get: docker-image-go-builder
    - get: fission-go-add-risk-data-src
      trigger: true
    - get: fission-go-compute-weather-risk-src
      trigger: true
    - get: fission-go-form-req-transformer-src
      trigger: true
    - get: fission-go-register-ticket-src
      trigger: true
    - get: fission-go-weather-data-src
      trigger: true
    - get: oic-ci-tasks-src

  - task: build-add-risk-data
    image: docker-image-go-builder
    file: oic-ci-tasks-src/function/build/build_function.yaml
    input_mapping: 
      task-src: oic-ci-tasks-src
      function-src: fission-go-add-risk-data-src
    params:
      FUNCTION_ENVIRONMENT: go
      FUNCTION_NAME: add-risk-data
      CODE_PATH: function-src/add-risk-data.go
  - task: publish-add-risk-data-to-staging
    image: docker-image-fission-cli
    file: oic-ci-tasks-src/function/publish/publish_function.yaml
    params: 
      ENVIRONMENT: wfstaging
      FISSION_URL: ((fission-url))
      FISSION_ROUTER: ((fission-router))
      FUNCTION_NAME: add-risk-data
      FUNCTION_ENVIRONMENT: go
      CODE_PATH: function-src/add-risk-data.so
      FUNCTION_METHOD: POST
    input_mapping: 
      task-src: oic-ci-tasks-src
      function-src: built-artifacts

  - task: build-compute-weather-risk
    image: docker-image-go-builder
    file: oic-ci-tasks-src/function/build/build_function.yaml
    input_mapping: 
      task-src: oic-ci-tasks-src
      function-src: fission-go-compute-weather-risk-src
    params:
      FUNCTION_ENVIRONMENT: go
      FUNCTION_NAME: compute-weather-risk
      CODE_PATH: function-src/compute-weather-risk.go
  - task: publish-compute-weather-risk-to-staging
    image: docker-image-fission-cli
    file: oic-ci-tasks-src/function/publish/publish_function.yaml
    params: 
      ENVIRONMENT: wfstaging
      FISSION_URL: ((fission-url))
      FISSION_ROUTER: ((fission-router))
      FUNCTION_NAME: compute-weather-risk
      FUNCTION_ENVIRONMENT: go
      CODE_PATH: function-src/compute-weather-risk.so
      FUNCTION_METHOD: POST
    input_mapping: 
      task-src: oic-ci-tasks-src
      function-src: built-artifacts

  - task: build-form-req-transformer
    image: docker-image-go-builder
    file: oic-ci-tasks-src/function/build/build_function.yaml
    input_mapping: 
      task-src: oic-ci-tasks-src
      function-src: fission-go-form-req-transformer-src
    params:
      FUNCTION_ENVIRONMENT: go
      FUNCTION_NAME: form-req-transformer
      CODE_PATH: function-src/form-req-transformer.go
  - task: publish-form-req-transformer-to-staging
    image: docker-image-fission-cli
    file: oic-ci-tasks-src/function/publish/publish_function.yaml
    params: 
      ENVIRONMENT: wfstaging
      FISSION_URL: ((fission-url))
      FISSION_ROUTER: ((fission-router))
      FUNCTION_NAME: form-req-transformer
      FUNCTION_ENVIRONMENT: go
      CODE_PATH: function-src/form-req-transformer.so
      FUNCTION_METHOD: POST
    input_mapping: 
      task-src: oic-ci-tasks-src
      function-src: built-artifacts

  - task: build-register-ticket
    image: docker-image-go-builder
    file: oic-ci-tasks-src/function/build/build_function.yaml
    input_mapping: 
      task-src: oic-ci-tasks-src
      function-src: fission-go-register-ticket-src
    params:
      FUNCTION_ENVIRONMENT: go
      FUNCTION_NAME: register-ticket
      CODE_PATH: function-src/register-ticket.go
  - task: publish-register-ticket-to-staging
    image: docker-image-fission-cli
    file: oic-ci-tasks-src/function/publish/publish_function.yaml
    params: 
      ENVIRONMENT: wfstaging
      FISSION_URL: ((fission-url))
      FISSION_ROUTER: ((fission-router))
      FUNCTION_NAME: register-ticket
      FUNCTION_ENVIRONMENT: go
      CODE_PATH: function-src/register-ticket.so
      FUNCTION_METHOD: POST
    input_mapping: 
      task-src: oic-ci-tasks-src
      function-src: built-artifacts

  - task: build-weather-data
    image: docker-image-go-builder
    file: oic-ci-tasks-src/function/build/build_function.yaml
    input_mapping: 
      task-src: oic-ci-tasks-src
      function-src: fission-go-weather-data-src
    params:
      FUNCTION_ENVIRONMENT: go
      FUNCTION_NAME: weather-data
      CODE_PATH: function-src/weather-data.go
  - task: publish-weather-data-to-staging
    image: docker-image-fission-cli
    file: oic-ci-tasks-src/function/publish/publish_function.yaml
    params: 
      ENVIRONMENT: wfstaging
      FISSION_URL: ((fission-url))
      FISSION_ROUTER: ((fission-router))
      FUNCTION_NAME: weather-data
      FUNCTION_ENVIRONMENT: go
      CODE_PATH: function-src/weather-data.so
      FUNCTION_METHOD: POST
    input_mapping: 
      task-src: oic-ci-tasks-src
      function-src: built-artifacts

- name: publish-workflow
  public: true
  plan:
  - aggregate:
    - get: docker-image-fission-cli
    - get: docker-image-newman
    - get: docker-image-wfcli
  - get: oic-ci-tasks-src
    passed: [ "publish-requirements" ]
  - get: fission-function-src
    trigger: true
  - task: build-workflow
    image: docker-image-wfcli
    file: oic-ci-tasks-src/workflow/build/build.yaml
    input_mapping: 
      task-src: oic-ci-tasks-src
      function-src: fission-function-src
    params:
      WORKFLOW_SRC: storm-surge.yaml
      ENVIRONMENT: wfstaging
  - task: publish-function-to-staging
    image: docker-image-fission-cli
    file: oic-ci-tasks-src/function/publish/publish_function.yaml
    params: 
      ENVIRONMENT: staging
      FISSION_URL: ((fission-url))
      FISSION_ROUTER: ((fission-router))
      FUNCTION_NAME: storm-surge
      FUNCTION_ENVIRONMENT: worfklow
      CODE_PATH: function-src/storm-surge.json
      FUNCTION_METHOD: POST
    input_mapping: 
      task-src: oic-ci-tasks-src
      function-src: built-artifacts
  - task: newman-test-function-in-staging
    attempts: 10
    image: docker-image-newman
    file: oic-ci-tasks-src/function/test/test_function.yaml
    input_mapping: 
      task-src: oic-ci-tasks-src
      function-src: fission-function-src
    params:
      FISSION_ROUTER: ((fission-router))
      ENVIRONMENT: wfstaging
      COLLECTION: function-src/ci/collection.json
      FUNCTION_NAME: storm-surge
      PROTOCOL: http
      TARGET_PORT: 80
      FUNCTION_METHOD: POST
  - aggregate: 
    - task: remove-function-from-staging
      image: docker-image-fission-cli
      file: oic-ci-tasks-src/function/remove/remove_function.yaml
      params: 
        ENVIRONMENT: wfstaging
        FISSION_URL: ((fission-url))
        FISSION_ROUTER: ((fission-router))
        FUNCTION_NAME: storm-surge
        FUNCTION_ENVIRONMENT: workflow
        FUNCTION_METHOD: POST
      input_mapping: 
        task-src: oic-ci-tasks-src
        function-src: fission-function-src
    - task: remove-add-risk-data
      image: docker-image-fission-cli
      file: oic-ci-tasks-src/function/remove/remove_function.yaml
      params: 
        ENVIRONMENT: wfstaging
        FISSION_URL: ((fission-url))
        FISSION_ROUTER: ((fission-router))
        FUNCTION_NAME: add-risk-data
        FUNCTION_ENVIRONMENT: go
        FUNCTION_METHOD: POST
      input_mapping: 
        task-src: oic-ci-tasks-src
        function-src: fission-function-src
    - task: remove-compute-weather-risk
      image: docker-image-fission-cli
      file: oic-ci-tasks-src/function/remove/remove_function.yaml
      params: 
        ENVIRONMENT: wfstaging
        FISSION_URL: ((fission-url))
        FISSION_ROUTER: ((fission-router))
        FUNCTION_NAME: compute-weather-risk
        FUNCTION_ENVIRONMENT: go
        FUNCTION_METHOD: POST
      input_mapping: 
        task-src: oic-ci-tasks-src
        function-src: fission-function-src
    - task: remove-form-req-transformer
      image: docker-image-fission-cli
      file: oic-ci-tasks-src/function/remove/remove_function.yaml
      params: 
        ENVIRONMENT: wfstaging
        FISSION_URL: ((fission-url))
        FISSION_ROUTER: ((fission-router))
        FUNCTION_NAME: form-req-transformer
        FUNCTION_ENVIRONMENT: go
        FUNCTION_METHOD: POST
      input_mapping: 
        task-src: oic-ci-tasks-src
        function-src: fission-function-src
    - task: remove-register-ticket
      image: docker-image-fission-cli
      file: oic-ci-tasks-src/function/remove/remove_function.yaml
      params: 
        ENVIRONMENT: wfstaging
        FISSION_URL: ((fission-url))
        FISSION_ROUTER: ((fission-router))
        FUNCTION_NAME: register-ticket
        FUNCTION_ENVIRONMENT: go
        FUNCTION_METHOD: POST
      input_mapping: 
        task-src: oic-ci-tasks-src
        function-src: fission-function-src
    - task: remove-weather-data
      image: docker-image-fission-cli
      file: oic-ci-tasks-src/function/remove/remove_function.yaml
      params: 
        ENVIRONMENT: wfstaging
        FISSION_URL: ((fission-url))
        FISSION_ROUTER: ((fission-router))
        FUNCTION_NAME: weather-data
        FUNCTION_ENVIRONMENT: go
        FUNCTION_METHOD: POST
      input_mapping: 
        task-src: oic-ci-tasks-src
        function-src: fission-function-src

- name: create-pr
  public: true
  plan:
  - aggregate:
    - get: fission-function-src
      trigger: true
      passed: [ "publish-workflow" ]
    - get: oic-ci-tasks-src
  - task: create-pr
    file: oic-ci-tasks-src/git/create_pr/create_pr.yaml
    input_mapping: 
      task-src: oic-ci-tasks-src
    params:
      GITHUB_ACCESS_TOKEN: ((gh-access-token))
      REPO_NAME: OpenIndustryCloud/fission-wf-storm-surge
      BASE_BRANCH: test-merge

- name: merge-pr
  plan:
  - get: fission-function-src
    passed: [ 'create-pr' ]
  - get: fission-function-merge-pr
    trigger: true
  - put: fission-function-merge-pr
    params:
      path: fission-function-merge-pr
      status: success
      merge:
        method: merge
        commit_msg: fission-function-merge-pr/LAST_MERGE.md

- name: test-pr
  plan:
  - get: fission-function-pr
    trigger: true
    version: every
  - get: docker-image-wfcli
  - get: oic-ci-tasks-src
  - task: build-workflow
    image: docker-image-wfcli
    file: oic-ci-tasks-src/workflow/build/build.yaml
    input_mapping: 
      task-src: oic-ci-tasks-src
      function-src: fission-function-src
    params:
      WORKFLOW: storm-surge.yaml
      ENVIRONMENT: unit-test
    on_success:
      put: fission-function-pr
      params:
        path: fission-function-pr
        status: success
    on_failure:
      put: fission-function-pr
      params:
        path: fission-function-pr
        status: failure

- name: release
  plan:
  - get: fission-function-src
    passed: [ 'merge-pr' ]
  - task: next-tag
    config:
      image_resource:
        type: docker-image
        source:
          repository: concourse/git-resource
      platform: linux
      inputs:
      - name: fission-function-src
      outputs:
      - name: tag
      run:
        path: bash
        args:
          - -c
          - |
            set -eux
            [ -d "tag" ] && mkdir -p tag
            echo v > tag/prefix
            pushd fission-function-src
              # git tag -l | sed -e "s/v//" | sort -n | tail -n 1 | xargs -n 1 expr 1 + | tee ../tag/name
              if [ "x$(git tag -l)" = "x" ]; then 
                echo 1 | tee ../tag/name 
              else 
                git tag -l | sed -e "s/v//" | sort -n | tail -n 1 | xargs -n 1 expr 1 + | tee ../tag/name
              fi
            popd
  - put: fission-function-src
    params:
      repository: fission-function-src
      only_tag: true
      tag: tag/name
      tag_prefix: v

